### ISSUE TITLE
Redundant information in MDB_cursor

### ISSUE THREAD

**Issue by andrewthad** [dmbarbour/haskell-lmdb#1]
First of all, thanks for writing these bindings. This is really well done, and as someone working on writing a higher level interface, this is a great foundation to build on top of.

The question I have concerns `MDB_cursor`. It is defined as:

```
data MDB_cursor = MDB_cursor
    { _crs_ptr :: {-# UNPACK #-} !(Ptr MDB_cursor)
    , _crs_dbi :: {-# UNPACK #-} !MDB_dbi
    , _crs_txn :: !MDB_txn
    }
```

There are two things about this that I don't understand well. The first is why the pointer is to the same data type. There is no `Storable` instance for `MDB_cursor`, so I'm guessing you are just using this as a placeholder. If this understanding is right, any type could have been used as the argument of `Ptr`, including a type with a `Storable` instance that would actually match the [actual MDB_cursor implementation](http://104.237.133.194/doc/group__internal.html#structMDB__cursor). My guess is that since you never needed to dereference this pointer in haskell, there was no value in doing this. I would like to know if my hunch is correct or if there was a different reason.

Additionally, the `MDB_cursor` data type duplicates information. The transaction handle and the dbi handle both show up in the haskell data type you have written and in the c structure that `MDB_cursor` points to. From the comments in your code, I can tell that you originally considered an implementation that avoids this duplication. In the ffi code, I found commented out implementations of `mdb_cursor_txn` and `mdb_cursor_dbi`:

```
foreign import ccall safe "lmdb.h mdb_cursor_del" _mdb_cursor_del :: Ptr MDB_cursor -> MDB_WriteFlags -> IO CInt
foreign import ccall safe "lmdb.h mdb_cursor_count" _mdb_cursor_count :: Ptr MDB_cursor -> Ptr CSize -> IO CInt
-- foreign import ccall safe "lmdb.h mdb_cursor_txn" _mdb_cursor_txn :: Ptr MDB_cursor -> IO (Ptr MDB_txn)
-- foreign import ccall safe "lmdb.h mdb_cursor_dbi" _mdb_cursor_dbi :: Ptr MDB_cursor -> IO MDB_dbi
```

Why did you decide against this approach? Was it speed or was it specifics of what you built this library for? I would appreciate hearing any insights you have.

**Comment by dmbarbour** [comment]
Sorry for the delay on response. I don't pay nearly enough attention to github issues reports, a consequence of watching too many other projects. Anyhow, answers.

Use of cyclic `Ptr MDB_cursor` here follows conventions I've seen elsewhere for working with opaque data structures. 

The "actual MDB_cursor implementation" you reference is not exposed through the LMDB API. You referenced internal documentation.

I associate metadata with `MDB_txn` because it's useful to have for some operations, stuff that cannot be recovered from a `Ptr MDB_txn`. So use of `_crs_txn` was necessary. I don't recall my exact thinking for `_crs_dbi`, but it was probably just a decision to be consistent about how I represent associated data.
