### ISSUE TITLE
Issue with opening a new database

### ISSUE THREAD

**Issue by KasperJanssens** [dmbarbour/haskell-lmdb#2]
When opening a new named database we seem to be running into an issue, presumably in the bindings as we don't have that kind of issue in our OCaml code base using the same flow of the script. The error is MDB_BAD_VALSIZE, which seems to have something to do with the database name ('A' in this case) being too large or so. The liblmdb-dev version is 0.9.10-1, ubuntu 14.04.1. 

```
#!/usr/bin/env stack
-- stack runghc --resolver nightly-2016-11-25 --install-ghc


{-# LANGUAGE OverloadedStrings #-}

import qualified Database.LMDB.Raw as Lmdb
import qualified Control.Concurrent as Concurrent

main :: IO ()
main = do
  let env_flags = []
  env <- Lmdb.mdb_env_create
  Lmdb.mdb_env_set_maxdbs env 2
  Lmdb.mdb_env_open env "/home/user/lmdb_hs/" env_flags
  Concurrent.runInBoundThread $ do
    txn <- Lmdb.mdb_txn_begin env Nothing False
    dbi <- Lmdb.mdb_dbi_open' txn (Just "A") [Lmdb.MDB_CREATE]
    Lmdb.mdb_dbi_close' env dbi
    Lmdb.mdb_txn_commit txn
  Lmdb.mdb_env_close env
```

**Comment by andrewthad** [comment]
Try this instead:

    {-# LANGUAGE OverloadedStrings #-}
    
    import qualified Database.LMDB.Raw as Lmdb
    import qualified Control.Concurrent as Concurrent

    main :: IO ()
    main =
      Concurrent.runInBoundThread $ do
        let env_flags = []
        env <- Lmdb.mdb_env_create
        Lmdb.mdb_env_set_mapsize env 1000000
        Lmdb.mdb_env_set_maxreaders env 5
        Lmdb.mdb_env_set_maxdbs env 4
        Lmdb.mdb_env_open env "the_env" env_flags
        txn <- Lmdb.mdb_txn_begin env Nothing False
        dbi <- Lmdb.mdb_dbi_open' txn (Just "A") [Lmdb.MDB_CREATE]
        Lmdb.mdb_txn_commit txn
        Lmdb.mdb_dbi_close' env dbi
        Lmdb.mdb_env_close env

LMBD has a somewhat confusing procedure for initialization. You need to open up a transaction, open all the databases, and then commit the transaction. This is weird because you end up using the database handle outside of the transaction in which it was opened. This is documented in the [haddocks for mdb_env_open](http://hackage.haskell.org/package/lmdb-0.2.5/docs/Database-LMDB-Raw.html#v:mdb_env_open). Also, as the docs explain, you have to call `mdb_env_set_mapsize`.

Since, this is all kind of annoying, I wrote [lmdb-high-level](http://hackage.haskell.org/package/lmdb-high-level), which prevents these kinds of issues from happening. But, it's not well documented and may not be suitable for your use case.

**Comment by KasperJanssens** [comment]
Indeed, didn't notice the fact that I closed the env and then did the the commit, I knew I must have been missing something silly as this (nearly) same snippet runs in our OCaML code base. I know about the mapsize and such, removed it from the little example to make it as small as possible, but thanks for the info. I might check out the high level package then, we use something similar from our OCaML bindings, usually practical. Bit of a weird exception, and a bit unexpected that it only shows when also having to create a database ( when filling in 'Nothing' instead of 'Just "A"' the first snippet runs. Thanks!
